/**
 * @file    can_uart_transport.h
 * @brief   UART 协议 payload 经 CAN 分片传输（与底盘 PawDrive-Base-Controller 一致）
 *
 * CAN ID = CAN_UART_ID_BASE + UART TYPE（如 0x8B → 0x48B）
 * 每帧 Data[8]: [frag_idx][frag_total][6B payload 片段]
 */
#ifndef CAN_UART_TRANSPORT_H
#define CAN_UART_TRANSPORT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define CAN_UART_ID_BASE              0x400u
#define CAN_UART_FRAG_DATA_BYTES      6u

/** UART TYPE_REPORT_BATTERY_STATE */
#define CAN_UART_MSG_BATTERY          0x8Bu
#define CAN_UART_ID_BATTERY           (CAN_UART_ID_BASE + CAN_UART_MSG_BATTERY)

#define CAN_UART_BATTERY_PAYLOAD_LEN    20u
#define CAN_UART_BATTERY_FRAG_TOTAL \
    ((CAN_UART_BATTERY_PAYLOAD_LEN + CAN_UART_FRAG_DATA_BYTES - 1u) / CAN_UART_FRAG_DATA_BYTES)

/** UART TYPE_REPORT_BATTERY_EXT（407 uart_protocol.h 待增 0x9A） */
#define CAN_UART_MSG_BATTERY_EXT        0x9Au
#define CAN_UART_ID_BATTERY_EXT         (CAN_UART_ID_BASE + CAN_UART_MSG_BATTERY_EXT)

#define CAN_UART_BATTERY_EXT_PAYLOAD_LEN  32u
#define CAN_UART_BATTERY_EXT_FRAG_TOTAL \
    ((CAN_UART_BATTERY_EXT_PAYLOAD_LEN + CAN_UART_FRAG_DATA_BYTES - 1u) / CAN_UART_FRAG_DATA_BYTES)

/** UART TYPE_REPORT_BATTERY_BALANCE */
#define CAN_UART_MSG_BATTERY_BALANCE      0x9Bu
#define CAN_UART_ID_BATTERY_BALANCE       (CAN_UART_ID_BASE + CAN_UART_MSG_BATTERY_BALANCE)

#define CAN_UART_BATTERY_BALANCE_PAYLOAD_LEN  8u
#define CAN_UART_BATTERY_BALANCE_FRAG_TOTAL \
    ((CAN_UART_BATTERY_BALANCE_PAYLOAD_LEN + CAN_UART_FRAG_DATA_BYTES - 1u) / CAN_UART_FRAG_DATA_BYTES)

/** UART TYPE_SET_CHARGE_CTRL（407 → BMS） */
#define CAN_UART_MSG_CHARGE_CTRL          0x41u
#define CAN_UART_ID_CHARGE_CTRL           (CAN_UART_ID_BASE + CAN_UART_MSG_CHARGE_CTRL)

#define CAN_UART_CHARGE_CTRL_PAYLOAD_LEN    3u
#define CAN_UART_CHARGE_CTRL_FRAG_TOTAL \
    ((CAN_UART_CHARGE_CTRL_PAYLOAD_LEN + CAN_UART_FRAG_DATA_BYTES - 1u) / CAN_UART_FRAG_DATA_BYTES)

/** UART TYPE_CMD_CHARGE / RSP_CHARGE（单帧 8 B，不分片） */
#define CAN_UART_MSG_CHARGE_CMD           0xA0u
#define CAN_UART_ID_CHARGE_CMD            (CAN_UART_ID_BASE + CAN_UART_MSG_CHARGE_CMD)
#define CAN_UART_MSG_CHARGE_RSP           0xA1u
#define CAN_UART_ID_CHARGE_RSP            (CAN_UART_ID_BASE + CAN_UART_MSG_CHARGE_RSP)

#ifdef __cplusplus
}
#endif

#endif /* CAN_UART_TRANSPORT_H */
